name: SmartMoving
version: '${version}'
main: com.github.ipecter.smartmoving.SmartMoving
api-version: 1.14
softdepend: [ PlaceholderAPI, WorldGuard ]
authors: [ IPECTER ]
description: SmartMoving Plugin
commands:
  smartmoving: