name: SmartMoving
version: '${version}'
main: com.github.ipecter.smartmoving.SmartMoving
description: SmartMoving Plugin
api-version: 1.14
authors: [ IPECTER ]
permissions:
  smartmoving:
    dash.use:
      default: true
    walljump.use:
      default: true
    crawling.use:
      default: true
commands:
  smartmoving:
softdepend: [ PlaceholderAPI, WorldGuard ]