name: SmartMoving
version: '${version}'
main: com.github.ipecter.rtu.smartmoving.SmartMoving
api-version: 1.14
softdepend: [ PlaceholderAPI ]
authors: [ IPECTER ]
description: SmartMoving Plugin
commands:
  smartmoving: