#Control whether to enable this plugin's functions
#이 플러그인의 기능을 활성화할 것인지 조정합니다
enablePlugin: true

#Message Locale
# Locale_KR.yml = KR
#메세지 언어, 새로운 언어 파일을 만들 수 있습니다, Locale_KR.yml = KR
locale: "EN"

#For Development
#개발 전용
debug: false

#Permission(Default=true): smartmoving.crawling.use
#권한(기본값=true): smartmoving.crawling.use
crawling:
  #HOLD - players will continue crawling as long as they keep shift pressed | Shift 키를 오랫동안 누르고 있으면 엎드립니다
  #TOGGLE - players will start crawling and get up when they press shift | Shift 키를 클릭하면 엎드리고 일어섭니다
  #TUNNELS - players can enter one block tunnels by sneaking in front of them | 앞에 한 칸 크기의 공간이 있을시 자동으로 엎드립니다
  modes:
    - "HOLD"
    - "TOGGLE"
    - "TUNNELS"

  #DOUBLE_SHIFT - double shift while looking down | 최대한 아래를 본 상태로 Shift를 더블 클릭하면 작동합니다
  #HOLD_X - hold shift for X seconds while looking down. Examples: 'HOLD_1', 'HOLD_0.5' | 최대한 아래를 본 상태로 Shift 키를 X 초 동안 홀드하고 있으면 작동합니다. 예: 'HOLD_1', 'HOLD_0.5'
  key: "DOUBLE_SHIFT"

  list:
    #If false, it will work as a whiteList | 만약 false인 경우, 화이트리스트로 작동합니다
    worldBlackList: true
    worlds:
      - disableWorld
    blockBlackList: true
    blocks:
      - MAGMA_BLOCK

#Permission(Default=true): smartmoving.walljump.use
#권한(기본값=true): smartmoving.walljump.use
wallJump:
  requireDirectionChange: true
  minimumDistance: 0.3
  maximumVelocity: -1
  maxJumps: 0
  timeOnWall: 0.6

  jumpPower:
    horizontal: 0.3
    vertical: 0.5

  slide:
    enable: true
    speed: 0.17
    canJumpWhile: true

  sound:
    namespace: "minecraft"
    #Break / Step / Place / Hit / Fall
    group: "Step"
    volume: 1.0
    pitch: 1.0

  list:
    #If false, it will work as a whiteList | 만약 false인 경우, 화이트리스트로 작동합니다
    worldBlackList: true
    worlds:
      - disableWorld
    blockBlackList: true
    blocks:
      - ICE
      - BLUE_ICE
      - PACKED_ICE
      - GLASS
      - WHITE_STAINED_GLASS
      - ORANGE_STAINED_GLASS
      - MAGENTA_STAINED_GLASS
      - LIGHT_BLUE_STAINED_GLASS
      - YELLOW_STAINED_GLASS
      - LIME_STAINED_GLASS
      - PINK_STAINED_GLASS
      - GRAY_STAINED_GLASS
      - LIGHT_GRAY_STAINED_GLASS
      - CYAN_STAINED_GLASS
      - PURPLE_STAINED_GLASS
      - BLUE_STAINED_GLASS
      - BROWN_STAINED_GLASS
      - GREEN_STAINED_GLASS
      - RED_STAINED_GLASS
      - BLACK_STAINED_GLASS
      - CACTUS